---
title: "Project Outline Form"
format: 
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    #documentclass: report
    mainfont: "Spectral" # https://fonts.google.com/specimen/Spectral
    sansfont: "Roboto"   # https://fonts.google.com/specimen/Roboto
    monofont: "Inconsolata" # https://fonts.google.com/specimen/Inconsolata
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: true
    colorlinks: true
    highlight-style: github
---

This form is intended to help you organise your thoughts and to develop an outline that can be used: a) to ensure that the group as a whole understands and agrees the briefing topic; and b) to share with the lecturer for high-level feedback. Filling in this form is *not* mandatory and you will not be graded. For each of the questions below, try to anticipate problems, questions that the intended audience might have, and practical issues for your group of deadlines and travel, 

Futhermore, the development of a good outline does not guarantee a good mark on the final submission, nor does robust feedback imply failure; rather, it is a chance to triangulate the briefing’s aims, agree a workplan, and begin collaborating on the final assessment *before* you disperse at the end of the Term.

If your group would like feedback on your outline, please have it ready by midway through the final ‘live’ session.  

## Project Summary

### What is the briefing topic?

*In two sentences, outline your briefing topic for the intended audience.*  

Research Question: 

Is there a relationship between types of gentrification and the concentration of professional airbnb hosts?

Is professionalisation related to factors of gentrification and culture? 

is there a relationship between professionalisation and types of gentrification, specifically focusing on cultural gentrification? 



### How will it meet the assessment’s stated aims?

*Why would this topic be of interest to the intended audience?*

### What data sets does it use?

*What data will this briefing require in order to achieve its aims and what are the strengths and limitations of these data?*

- Inside Airbnb dataset
- Cultural infrastructure points (GLA)
- Yee/Dennett gentrification classifications (published analysis of census data)

### What techniques do you expect to use?

*Which of the techniques covered in-class (or **not** in class!) do you expect to use in order to write the briefing and why?*

- Multiple linear regression

### What findings do you expect and how will you present them?

*On the assumption that you find **what you expect**, how will you organise and present your findings in a succinct, compelling way?*

### Workplan

*Discuss and agree who will do what, and how you will coordinate your activity to ensure that your briefing is completed in time.*  


| Task  | Contributor  |  Status |
|---|---|---|
| Project design/proposal  |  All | Complete  |
| Load and clean Airbnb data  | ZPE, MH  |  Complete |
| Load and clean Cultural points data  | GY, JP |  Complete |
| Logistic regression analysis | MH, ZPE | In progress |
| Multi-linear regression analysis | JP, ZPE | --- |
| Authoring: Background + Lit review |GY, MH|---|
| Authoring: Results/Discussion |---|---|
| Authoring: Methodology + Data |---|---|

## Report Structure

1.    Executive Summary (~250)
2.    Background (~650)



Airbnbs cluster for different reasons. Difficult to answer what came first – gentrification or Airbnb: https://www.sciencedirect.com/science/article/pii/S0197397522000790

 

Wachsmuth, D. and Weisler, A. (2018) find that Airbnb drove a meaningful and significant rent gap in NYC:  ‘Airbnb and the rent gap: Gentrification

through the sharing economy’, *Environment and Planning A: Economy and Space*,

50(6), pp. 1147–1170. doi: 10.1177/0308518X18778038.



1.    Objectives (~200)
2.    Summary of Key Findings (~200)
3.    Extended Results/Policy Discussion (~850)
4.    Conclusion (~250)
5.    Appendix: Methodology & Data (~100)
6.    References





